version: '2'
services:
  jenkins:
    build: .
    image: zirtrex/jenkins:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
 
volumes:
  jenkins_home: